name: alphapy

channels:
 - conda-forge

dependencies:
- bokeh>=1.3
- ipython>=7.2
- keras>=2.3.1
- matplotlib>=3.0
- numpy>=1.17
- pandas>=1.0
- pyyaml>=5.0
- scikit-learn>=0.23.1
- scipy==1.4.1
- seaborn>=0.9
- tensorflow>=2.0
- pip:
  - arrow>=0.13
  - category_encoders>=2.1
  - iexfinance>=0.4.3
  - imbalanced-learn>=0.5
  - pandas-datareader>=0.8
  - pyfolio>=0.9
  - sphinx-rtd-dark-mode>=1.3.0
  - sphinx_rtd_theme>=2.0
